name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2681e671e2e419349ea66166b9272a14c30b4ed9fe7c5d64b821e1932315cf09"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
