name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f200323cf3216bd70bf1799dd8e5fde319232b6eb84f963c9b29c4ceefa2d0cc"

[versions]
forge = "48.1.0"
minecraft = "1.20.2"
