name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4eb43185c36711e2e61d6a660047a28887760fbf7aa325accd2967f900049d8"

[versions]
forge = "48.1.0"
minecraft = "1.20.2"
