name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.43"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "942b6ba375ac1d8c2033f99505f5f10996661ee19c0108fb3563d1aca8122eac"

[versions]
forge = "48.1.0"
minecraft = "1.20.2"
