name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f6e70e02fedca07c6d0fe82901b6263e3d59372d556d498010c84fd088c8c4d"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
