name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8035c33417b26db76ffe4d659c08afc7836575dc80c9f7dfc6e39a6feaaaa6c"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
