name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45e1fc5b15702d90921ed0ab1d287f8b53453e622ae0a744d6e2e11ccc1db30e"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
