name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.40"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be318653c88ca4a9d9f6123458bdfc291f8e2f4d7abb11535bdbd000fdb1c398"

[versions]
forge = "48.1.0"
minecraft = "1.20.2"
