name = "Pixelpacked"
author = "Jeef"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b9952f7e6287e470dcd60bef41b8b7939a2e9af00cc1d63fcaeefcbb960380f"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
unsup = "0.2.3"
