name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aab234d88ee642e7780a9d3f79ad655d4c799c62be10a39b00d3c050ae233883"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
