name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b029020e65b689fd63abbf22f11354f7cdd8e0dc712d254b8f64cb669c0baeef"

[versions]
forge = "48.1.0"
minecraft = "1.20.2"
