name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4b6114e386bb3b249562574da697b9a6f96a11317fae1e477d660efc97a17ee"

[versions]
forge = "48.1.0"
minecraft = "1.20.2"
