name = "Pixelmon Pack"
author = "Jeef"
version = "1.0.45"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc5bd8df54151996d28c4d17ad63cfa70ae08845701e940ae2a2406f22018eec"

[versions]
forge = "48.1.0"
minecraft = "1.20.2"
